# Generated by Django 6.0.2 on 2026-02-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, choices=[('general_physician', 'General Physician (MBBS, MD Internal Medicine)'), ('neuro_ortho', 'Neuro-Ortho Specialist'), ('cardiologist', 'Cardiologist (DM Cardiology)'), ('dermatology', 'Dermato-Endocrine-Gyne Specialist (MD Dermatology)')], max_length=255, null=True),
        ),
    ]
