services:
  redis:
    image: "redis:latest"
    container_name: redis_server
   

    env_file:
      - .env

    ports:
      - "6379:6379"
     
    volumes:
      - redis_data:/data

    restart: unless-stopped

  djangoproject:
    image: django-img
    
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    build: 
      context: ..
      dockerfile: system/dockerfile
    container_name: django

    env_file:
      - .env

    ports:
      - "8000:8000"
      
    volumes:
      - ../system:/app

    depends_on:
      - redis 

    restart: unless-stopped

  celery:
    image: django-img
    container_name: celery
    command: sh -c "python -m celery -A system worker --loglevel=info"

    env_file:
      - .env

    volumes:
      - ../system:/app

    depends_on:
      - redis
      - djangoproject

    restart: unless-stopped

   
  celery-beat:
     image: django-img
     container_name: celery-beat
     command: sh -c "python -m celery -A system beat --loglevel=info"
  
     env_file:
       - .env
  
     volumes:
       - ../system:/app
  
     depends_on:
      - redis
      - djangoproject
  
     restart: unless-stopped

volumes:
  redis_data:






    